services:
  django: 
    build: .
    container_name: django
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4:8.14.0
    env_file:
      - .env
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    ports:
      - "8082:80"
    depends_on:
      - db

  redis:
    image: redis:alpine
    environment:
      REDIS_REPLICATION_MODE: master
    volumes:
      - ./redis_data:/data
    command: redis-server --appendonly yes